# Generated by Django 5.0.6 on 2024-05-15 00:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(default='nombre default', max_length=100)),
                ('sueldo', models.DecimalField(decimal_places=2, default=1000, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('letra', models.CharField(default='A', max_length=100)),
                ('maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salones', to='entidades.maestro')),
            ],
        ),
    ]
